version: '2'
services:
#
# Zookeeper Service
#
  zookeeper:
    tty: true
    image: rawmind/alpine-zk:3.4.9
    restart: always
    ports:
      - 2181:2181/tcp
    volumes_from:
      - zookeeper-volume
      - zookeeper-conf
    environment:
      - JVMFLAGS=-Xmx1000m -Xms1000m
      - ZK_DATA_DIR=/opt/zk/data
      - ZK_INIT_LIMIT=10
      - ZK_MAX_CLIENT_CXNS=500
      - ZK_SYNC_LIMIT=10
      - ZK_TICK_TIME=10000
    labels: 
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: zookeeper-volume, zookeeper-conf
  zookeeper-conf:
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    image: rawmind/rancher-zk:3.4.8-5
    volumes:
      - /opt/tools
  zookeeper-volume:
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    environment:
      - SERVICE_UID=10002
      - SERVICE_GID=10002
      - SERVICE_VOLUME=/opt/zk/data
    volumes:
      - /opt/zk/data
    volume_driver: local
    image: rawmind/alpine-volume:0.0.2-1
#
# Kafka Service
#
  kafkabroker:
    tty: true
    image: rawmind/alpine-kafka:0.10.2.0-2
    ports:
      - 9092:9092/tcp
      - 9093:9093/tcp
    restart: always
    volumes_from:
      - kafkabroker-volume
      - kafkabroker-conf
    environment:
      - JVMFLAGS=-Xmx2500m -Xms2500m
      - CONFD_INTERVAL=60
      - JMX_PORT=9093
      - ZK_SERVICE=zookeeper
      - KAFKA_DELETE_TOPICS=true
      - KAFKA_LOG_DIRS=/opt/kafka/logs
      - KAFKA_LOG_RETENTION_HOURS=168
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_NUM_REPLICATION=3
      - ADVERTISE_PUB_IP=true
    links:
      - zookeeper:zookeeper
    labels: 
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: kafkabroker-volume, kafkabroker-conf
  kafkabroker-conf:
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    image: apptivo/rancher-kafka:0.10.2.0-2
    volumes:
      - /opt/tools
  kafkabroker-volume:
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    environment:
      - SERVICE_UID=10003
      - SERVICE_GID=10003
      - SERVICE_VOLUME=/opt/kafka/logs
    volumes:
      - /opt/kafka/logs
    volume_driver: local
    image: rawmind/alpine-volume:0.0.2-1
#
# Kafka-feeds Service   ## additional kafka-broker
#
#  kafkabroker-feeds:
#    tty: true
#    image: rawmind/alpine-kafka:0.10.2.0-2
#    ports:
#      - 9094:9092/tcp
#      - 9095:9093/tcp
#    restart: always
#    volumes_from:
#      - kafkabroker-feeds-volume
#      - kafkabroker-feeds-conf
#    environment:
#      - JVMFLAGS=-Xmx2500m -Xms2500m
#      - CONFD_INTERVAL=60
#      - JMX_PORT=9093
#      - ZK_SERVICE=zookeeper
#      - KAFKA_DELETE_TOPICS=true
#      - KAFKA_LOG_DIRS=/opt/kafka/logs
#      - KAFKA_LOG_RETENTION_HOURS=168
#      - KAFKA_NUM_PARTITIONS=3
#      - KAFKA_NUM_REPLICATION=3
#      - ADVERTISE_PUB_IP=true
#    links:
#      - zookeeper:zookeeper
#    labels: 
#      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
#      io.rancher.container.hostname_override: container_name
#      io.rancher.sidekicks: kafkabroker-feeds-volume, kafkabroker-feeds-conf
#  kafkabroker-feeds-conf:
#    labels:
#      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
#      io.rancher.container.hostname_override: container_name
#      io.rancher.container.start_once: true
#    image: apptivo/rancher-kafka:0.10.2.0-2
#    volumes:
#      - /opt/tools
#  kafkabroker-feeds-volume:
#    labels:
#      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
#      io.rancher.container.hostname_override: container_name
#      io.rancher.container.start_once: true
#    environment:
#      - SERVICE_UID=10003
#      - SERVICE_GID=10003
#      - SERVICE_VOLUME=/opt/kafka/logs
#    volumes:
#      - /opt/kafka/logs
#    volume_driver: local
#    image: rawmind/alpine-volume:0.0.2-1
#
# JMX monitoring 
#
  kafka-jmx-exporter:
    image: apptivo/prometheus-jmx-exporter:0.0.9 
    ports: 
      - "8081:8081"  
    links:
      - kafkabroker:kafka
#      - kafkabroker-feeds:kafka-feeds
    environment:
      - JMX_PORT=9093
      - HTTP_PORT=8081
      - JMX_EXPORTER_CONFIG_FILE=kafka.yml
    labels: 
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
#
# Postfix service
#
  postfix:
    image: apptivo/monit-postfix:0.3.2
    tty: true
    stdin_open: true
    dns:
    - ${DNS_IP_VAL}
    volumes:
      - maildata:/var/spool/postfix/
      - maillog:/var/log/mail/
    volumes_from:
      - postfix-conf
    environment:
      - TOPIC_NAME=${TOPIC_VALUE}
      - DB_IP=${DB_IP_VAL}
    links:
      - kafkabroker:kafkabroker
 #     - kafkabroker-feeds:kafka-feeds
    labels:
      io.rancher.container.hostname_override: container_name
      #io.rancher.scheduler.affinity:host_label_soft: postfix=true
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: postfix-conf
  postfix-conf:
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    image: apptivo/dynamic-rsyslog:0.3.4
    volumes:
      - /opt/tools
  postfix-HA:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
      - 25:25/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.affinity:host_label: haproxy=true
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}

volumes:
  maildata:
    per_container: true
  maillog:
    per_container: true